baseURL = 'http://dev.fonorobert.com/'
languageCode = 'en-us'
title = 'Robert Fonó'
theme = 'fonorobert.com-theme'
[menus]
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 10
  [[menus.main]]
    name = 'Stories'
    pageRef = '/stories'
    weight = 20
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 30
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40
  [[menus.footer]]
    name = 'Now'
    pageRef = '/now'
    weight = 10
  [[menus.footer]]
    name = 'Instagram'
    url = 'https://instagram.com/fonorobert'
    weight = 20
  [[menus.footer]]
    name = 'Log'
    url = 'https://fono.day'
    weight = 30
[params]
  [params.imagesizes]
    thumb = '600x600'
    full = '1920x1920'
    feat = '400x400'