baseURL = 'http://dev.fonorobert.com/'
languageCode = 'en-us'
title = 'Robert Fono'
theme = 'fonorobert.com-theme'
[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Stories'
    pageRef = '/stories'
    weight = 10
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30
[params]
  [params.imagesizes]
    thumb = '600x600'
    full = '1280x1280'
    feat = '400x400'