baseURL = 'http://dev.fonorobert.com/'
languageCode = 'en-us'
title = 'Robert Fonó'
theme = 'fonorobert.com-theme'
[menus]
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 10
  [[menus.main]]
    name = 'Stories'
    pageRef = '/stories'
    weight = 20
  #[[menus.main]]
  #  name = 'Notes'
  #  pageRef = '/notes'
  #  weight = 30
  [[menus.footer]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 10
  [[menus.footer]]
    name = 'Instagram'
    url = 'https://instagram.com/fonorobert'
    weight = 20
  [[menus.footer]]
    name = 'Now'
    url = 'https://fono.day/now'
    weight = 30
  [[menus.footer]]
    name = 'Log'
    url = 'https://fono.day'
    weight = 40
[imaging]
  quality = 100
  anchor = 'Smart'
[params]
  [params.imagesizes]
    thumb = '600x600'
    full = '1920x1920'
    feat = '600x600'
