baseURL = 'http://dev.fonorobert.com/'
languageCode = 'en-us'
title = 'Robert Fono'
theme = 'fonorobert.com-theme'
[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Stories'
    pageRef = '/stories'
    weight = 30
[[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40
[[menus.main]]
    name = 'Log'
    pageRef = '/log'
    weight = 50